Instalação básica de kubernetes (k3s ou kind), argoCD e applicationset de exemplos (prometheus e rabbitmq)
lhc/k8s1 pull request #2
Opened 2024-11-08 00:08 UTC by andreyev

2024-11-10 17:56 UTC, marcpires commented
LGTM

2024-11-10 18:17 UTC, marcpires requested changes

2024-11-10 18:17 UTC, marcpires commented on applicationsets/prometheus.yaml
> +      project: default
Would create an o11y, observability or monitoring project instead of put all in default

2024-11-10 18:17 UTC, marcpires commented on applicationsets/rabbitmq.yaml
> +      project: default
Would create another project for this for best practices

2024-11-11 15:02 UTC, manasouza commented on README.md
> +curl -s https://raw.githubusercontent.com/lhc/k8s1/refs/heads/main/kind-install.sh | bash -x
The kubectl is not installed if I run only this right?

2024-11-11 21:47 UTC, andreyev commented on applicationsets/rabbitmq.yaml
> +      project: default
boa! fixed!

2024-11-11 21:47 UTC, andreyev commented on applicationsets/prometheus.yaml
> +      project: default
boa! fixed!

2024-11-11 21:47 UTC, andreyev commented on applicationsets/prometheus.yaml
> +        namespace: prometheus
boa! fixed!

2024-11-11 21:48 UTC, andreyev commented on README.md
> +curl -s https://raw.githubusercontent.com/lhc/k8s1/refs/heads/main/k3s-install.sh | bash -x
Hmmmm... Por enquanto vamos deixar !*nix-like pra v2 ;-)

2024-11-11 21:48 UTC, andreyev commented on README.md
> +curl -s https://raw.githubusercontent.com/lhc/k8s1/refs/heads/main/kind-install.sh | bash -x
sim, adicionei uma seção requisitos no começo, incluindo ele e o docker...

2024-11-11 22:40 UTC, manasouza approved these changes

2024-11-12 13:54 UTC, marcpires approved these changes
LGTM. Just add the links to Docker and kubectl installation in the requirement section

2024-11-12 13:54 UTC, marcpires commented on README.md
> +- Binários docker e kubectl
Add link to the docs. Otherwise LGTM

2024-11-16 16:03 UTC, manasouza commented on README.md
> +- Binários docker e kubectl
I've used this: https://kubernetes.io/docs/tasks/tools/install-kubectl-linux/

2024-11-19 16:15 UTC, EstevesDouglas approved these changes

2024-11-19 16:29 UTC, marcpires commented on README.md
> +- Binários docker e kubectl
Add this as a link in the requirements section

2024-12-11 21:35 UTC, EstevesDouglas approved these changes

2024-12-12 12:09 UTC, EstevesDouglas approved these changes

2024-12-12 12:13 UTC, EstevesDouglas reviewed
Ok.

2024-12-13 13:25 UTC, merged